# Values for nginx ingress controller
ingress-nginx:
  controller:
    service:
      type: LoadBalancer
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      proxy-body-size: "10m"
    metrics:
      enabled: false
  defaultBackend:
    enabled: false